(function(){
 const games=()=>window.ARCADE_GAMES||[], esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 const relative=iso=>{const n=(Date.now()-new Date(iso))/1000;if(n<60)return "just now";if(n<3600)return `${Math.floor(n/60)} minutes ago`;if(n<86400)return `${Math.floor(n/3600)} hours ago`;if(n<172800)return "yesterday";return `${Math.floor(n/86400)} days ago`};
 function render(){const root=document.querySelector("#passportContent");if(!root)return;const v=ArcadeStorage.load(),p=v.passport,rank=ArcadeProgress.rankFor(p.xp),rs=window.ARCADE_RANKS||[],i=rs.indexOf(rank),next=rs[i+1],pct=next?Math.max(0,Math.min(100,(p.xp-rank.xp)/(next.xp-rank.xp)*100)):100;const achievements=window.ARCADE_ACHIEVEMENTS||[];
 root.innerHTML=`<section class="passport-card"><p class="eyebrow">Nobody Creative / membership credential</p><div class="passport-id"><div class="passport-photo">N</div><div><label for="nickname">Employee alias</label><div class="nickname-row"><input id="nickname" maxlength="32" value="${esc(p.nickname)}"><button class="button button-secondary" id="saveNickname">Save</button></div><code>${esc(p.arcadeId)}</code></div></div><h3>${esc(rank.name)}</h3><div class="xp-label"><span>${p.xp} XP</span><span>${next?`${next.xp-p.xp} to ${next.name}`:"Maximum token privileges"}</span></div><div class="xp-track" role="progressbar" aria-label="XP toward next rank" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(pct)}"><span style="width:${pct}%"></span></div><div class="passport-stats"><span><strong>${p.launches}</strong> launches</span><span><strong>${Object.keys(p.games).length}</strong> explored</span><span><strong>${v.favorites.length}</strong> favorites</span><span><strong>${Object.values(v.challenges).filter(c=>c.completed).length}</strong> dailies</span></div></section>
 <section><h3>Your collections</h3><div class="collection-grid"><div><h4>♥ Favorites</h4><p>${v.favorites.map(id=>esc(games().find(g=>g.id===id)?.title)).join(", ")||"No favorites yet."}</p></div><div><h4>＋ Play Later</h4><p>${v.playLater.map(id=>esc(games().find(g=>g.id===id)?.title)).join(", ")||"The queue is suspiciously tidy."}</p></div></div></section>
 <section><h3>Achievement cabinet</h3><div class="achievement-grid">${achievements.map(a=>{const u=v.achievements[a.id];const hidden=a.secret&&!u;return `<article class="achievement ${u?"unlocked":"locked"}"><span>${hidden?"?":esc(a.icon)}</span><div><h4>${hidden?"Classified":esc(a.name)}</h4><p>${hidden?"This achievement was not approved by corporate.":esc(a.description)}</p><small>${u?`Unlocked ${new Date(u.unlockedAt).toLocaleDateString()} · `:""}${a.xp} XP</small></div></article>`}).join("")}</div></section>
 <section><h3>Recent activity</h3><ol class="activity-feed">${v.activity.map(a=>`<li title="${esc(new Date(a.at).toLocaleString())}"><span>${esc(a.text)}</span><time datetime="${esc(a.at)}">${relative(a.at)}</time></li>`).join("")||"<li>No activity yet. The machine is watching politely.</li>"}</ol></section>
 <section><h3>Settings & data</h3><div class="settings-grid"><label><input type="checkbox" data-setting="sound" ${v.settings.sound?"checked":""}> Sound effects</label><label><input type="checkbox" data-setting="reducedMotion" ${v.settings.reducedMotion?"checked":""}> Reduced animations</label><label><input type="checkbox" data-setting="autoplay" ${v.settings.autoplay?"checked":""}> Auto-play previews</label><label><input type="checkbox" data-setting="dataSaver" ${v.settings.dataSaver?"checked":""}> Data Saver</label></div><div class="settings-actions"><button class="button button-secondary" id="exportProgress">Export progress</button><label class="button button-secondary" for="importProgress">Import progress</label><input class="sr-only" id="importProgress" type="file" accept="application/json"><button class="button danger" id="resetProgress">Reset progress</button><button class="button button-secondary" id="installationHelp">Installation help</button></div><p id="dataMessage" role="status"></p><p class="setup-note">About: Nobody Arcade is a local-first playable portfolio. No account, ads, or third-party tracking.</p></section>`;
 document.querySelector("#saveNickname").onclick=()=>{const value=document.querySelector("#nickname").value.trim();if(!value)return;const x=ArcadeStorage.load();x.passport.nickname=value;ArcadeStorage.save(x);message("Nickname filed with management.")};
 document.querySelectorAll("[data-setting]").forEach(el=>el.onchange=()=>{const x=ArcadeStorage.load();x.settings[el.dataset.setting]=el.checked;ArcadeStorage.save(x);document.documentElement.classList.toggle("reduce-motion",x.settings.reducedMotion);message("Setting saved.")});
 document.querySelector("#exportProgress").onclick=()=>{const blob=new Blob([JSON.stringify(ArcadeStorage.exportData(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`nobody-arcade-passport-${ArcadeStorage.day()}.json`;a.click();URL.revokeObjectURL(a.href);message("Passport exported.")};
 document.querySelector("#importProgress").onchange=async e=>{try{const x=JSON.parse(await e.target.files[0].text());if(!ArcadeStorage.valid(x))throw Error();if(!confirm("Replace current arcade progress with this passport?"))return;delete x.exportDate;ArcadeStorage.save(x);render();message("Passport restored successfully.")}catch{message("That file is not a valid Phase 2 Arcade Passport.")}};
 document.querySelector("#resetProgress").onclick=()=>{if(confirm("Reset all arcade progress? This cannot be undone.")){localStorage.removeItem(ArcadeStorage.KEY);location.reload()}};
 document.querySelector("#installationHelp").onclick=()=>document.querySelector("#installButton")?.click();
 }
 function message(s){const el=document.querySelector("#dataMessage")||document.querySelector("#toast");if(el)el.textContent=s}
 window.ArcadePassport={render};window.addEventListener("arcade-state",()=>{if(document.querySelector("#passportDialog")?.open)render()});
})();
