(function(){
 const S=()=>ArcadeStorage.load(), save=v=>ArcadeStorage.save(v), games=()=>window.ARCADE_GAMES||[], defs=()=>window.ARCADE_ACHIEVEMENTS||[], ranks=()=>window.ARCADE_RANKS||[];
 const activity=(v,text,type="note")=>{v.activity.unshift({id:`${Date.now()}-${Math.random()}`,text,type,at:ArcadeStorage.iso()});v.activity=v.activity.slice(0,50)};
 function rankFor(xp){return [...ranks()].reverse().find(r=>xp>=r.xp)||ranks()[0]}
 function award(v,key,xp,text){if(v.awards[key])return false;const before=rankFor(v.passport.xp).name;v.awards[key]=ArcadeStorage.iso();v.passport.xp+=xp;if(text)activity(v,text);const after=rankFor(v.passport.xp).name;if(before!==after){activity(v,`Ranked up to ${after}`,"rank");window.dispatchEvent(new CustomEvent("arcade-rank",{detail:{rank:after}}))}return true}
 function condition(a,v){const p=v.passport,gamesPlayed=Object.keys(p.games);return a.condition==="launches"?p.launches>=a.target:a.condition==="caseStudies"?p.caseStudies.length>=a.target:a.condition==="uniqueGames"?gamesPlayed.length>=a.target:a.condition==="genres"?p.genres.length>=a.target:a.condition==="visitDays"?p.visitDays.length>=a.target:a.condition==="backRoom"?!!p.backRoomUnlocked:a.condition==="game"?!!p.games[a.gameId]:a.condition==="favorites"?v.favorites.length>=a.target:a.condition==="noControls"?!!p.noControlsLaunch:a.condition==="allPlayable"?games().filter(g=>!g.secret&&g.status==="Playable"&&g.playUrl).every(g=>p.games[g.id]):a.condition==="standalone"?!!p.standalone:a.condition==="rank"?ranks().findIndex(r=>r.name===rankFor(p.xp).name)>=ranks().findIndex(r=>r.name===a.rank):false}
 function check(v){defs().forEach(a=>{if(!v.achievements[a.id]&&condition(a,v)){v.achievements[a.id]={unlockedAt:ArcadeStorage.iso()};v.passport.xp+=a.xp;activity(v,`Unlocked ${a.name}`,"achievement");trackArcadeEvent("achievement_unlock",{achievementId:a.id});window.dispatchEvent(new CustomEvent("arcade-achievement",{detail:a}))}})}
 function today(v=S()){const date=ArcadeStorage.day(),pool=window.ARCADE_CHALLENGES||[],seed=[...date].reduce((n,c)=>((n*31)+c.charCodeAt(0))>>>0,7),def=pool[seed%pool.length];v.challenges[date]??={id:def.id,date,progress:0,completed:false};return {...def,...v.challenges[date]}}
 function challenge(v,type,game){const c=today(v);if(c.completed)return;let hit=c.type===type;if(c.type==="featured"&&type==="launch")hit=!!game?.featured;if(c.type==="genre"&&type==="launch")hit=game?.genres?.includes(c.genre);if(c.type==="newGame"&&type==="newGame")hit=true;if(c.type==="touch"&&type==="launch")hit=game?.mobileOptimized&&matchMedia("(max-width:760px)").matches;if(c.type==="distinctGames"&&type==="launch"){const row=v.challenges[c.date];row.games=[...new Set([...(row.games||[]),game.id])];row.progress=row.games.length;hit=false}if(hit)v.challenges[c.date].progress=Math.min(c.target,(v.challenges[c.date].progress||0)+1);if(v.challenges[c.date].progress>=c.target){v.challenges[c.date].completed=true;v.challenges[c.date].completedAt=ArcadeStorage.iso();v.passport.xp+=c.xp;activity(v,`Completed daily challenge: ${c.title}`,"challenge");trackArcadeEvent("daily_challenge_complete",{challengeId:c.id});window.dispatchEvent(new CustomEvent("arcade-challenge",{detail:c}))}}
 function init(){const v=S(),d=ArcadeStorage.day();if(!v.passport.visitDays.includes(d)){v.passport.visitDays.push(d);award(v,`return:${d}`,20,"Returned for another shift")}v.passport.lastVisit=ArcadeStorage.iso();if(!v.awards.firstVisit)award(v,"firstVisit",25,"Received an Arcade Passport");v.passport.standalone=matchMedia("(display-mode: standalone)").matches||navigator.standalone===true;check(v);save(v)}
 function launch(game,opts={}){const v=S(),old=!!v.passport.games[game.id],now=ArcadeStorage.iso(),last=v.passport.games[game.id]?.lastPlayed;v.passport.launches++;v.passport.games[game.id]={launches:(v.passport.games[game.id]?.launches||0)+1,lastPlayed:now};if(!old){v.passport.genres=[...new Set([...v.passport.genres,...game.genres])];award(v,`discover:${game.id}`,30,`Discovered ${game.title}`);challenge(v,"newGame",game)}if(!last||Date.now()-new Date(last)>300000)award(v,`launch:${game.id}:${ArcadeStorage.day()}`,10);if(!opts.controlsOpened)v.passport.noControlsLaunch=true;activity(v,`Played ${game.title}`,"play");challenge(v,"launch",game);check(v);save(v);trackArcadeEvent("game_launch",{gameId:game.id})}
 function favorite(game){const v=S(),on=!v.favorites.includes(game.id);v.favorites=on?[...v.favorites,game.id]:v.favorites.filter(id=>id!==game.id);if(on){award(v,`favorite:${game.id}`,10,`Favorited ${game.title}`);challenge(v,"favorite",game)}check(v);save(v);trackArcadeEvent("favorite",{gameId:game.id,on});return on}
 function later(game){const v=S(),on=!v.playLater.includes(game.id);v.playLater=on?[...v.playLater,game.id]:v.playLater.filter(id=>id!==game.id);save(v);trackArcadeEvent("play_later",{gameId:game.id,on});return on}
 function caseStudy(game){const v=S();if(!v.passport.caseStudies.includes(game.id)){v.passport.caseStudies.push(game.id);award(v,`case:${game.id}`,15,`Reviewed ${game.title} project notes`)}check(v);save(v);trackArcadeEvent("project_view",{gameId:game.id})}
 function backRoom(){const v=S();if(!v.passport.backRoomUnlocked){v.passport.backRoomUnlocked=true;award(v,"backRoom",75,"Entered the Back Room");challenge(v,"backRoom");check(v);save(v);trackArcadeEvent("back_room_discovery")}}
 window.ArcadeProgress={init,rankFor,today,launch,favorite,later,caseStudy,backRoom,check,challenge};
})();
