(() => {
  "use strict";
  const q=s=>document.querySelector(s),canvas=q("#game"),stage=q("#stage"),scoreEl=q("#score"),bestEl=q("#best"),timeEl=q("#time"),livesEl=q("#lives"),overlay=q("#overlay"),title=q("#overlayTitle"),copy=q("#overlayCopy"),startButton=q("#startButton"),muteButton=q("#mute");
  if(!canvas||!stage||!startButton) return;
  const ctx=canvas.getContext("2d");if(!ctx)return;
  const bestKey="nobodyArcade.tapePanicBest";let best=0;try{best=Number(localStorage.getItem(bestKey)||0)}catch{}bestEl.textContent=best;
  let running=false,raf=0,score=0,lives=3,time=45,last=0,spawnClock=0,secondClock=0,sound=false,tapes=[];const bin={x:380,y:485,w:140,h:42,targetX:450};
  function rounded(x,y,w,h,r){r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
  function resize(){const rect=stage.getBoundingClientRect(),w=rect.width||innerWidth||320,h=rect.height||Math.max(320,innerHeight*.7);const ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(2,Math.floor(w*ratio));canvas.height=Math.max(2,Math.floor(h*ratio));ctx.setTransform(canvas.width/900,0,0,canvas.height/560,0,0);draw()}
  function reset(){score=0;lives=3;time=45;tapes=[];spawnClock=secondClock=0;bin.x=380;bin.targetX=450;updateHud()}
  function updateHud(){scoreEl.textContent=score;timeEl.textContent=time;livesEl.textContent=Array.from({length:3},(_,i)=>i<lives?"♥":"·").join(" ")}
  function beep(freq,duration=.05){if(!sound)return;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;beep.ctx||=new Audio();const o=beep.ctx.createOscillator(),g=beep.ctx.createGain();o.frequency.value=freq;g.gain.value=.025;o.connect(g);g.connect(beep.ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,beep.ctx.currentTime+duration);o.stop(beep.ctx.currentTime+duration)}catch{}}
  function spawn(){const r=Math.random(),type=r>.9?"gold":r<.22?"cursed":"good";tapes.push({x:35+Math.random()*800,y:-50,w:70,h:42,speed:120+Math.random()*115+(45-time)*2.4,rotation:(Math.random()-.5)*.7,spin:(Math.random()-.5)*1.4,type})}
  const hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
  function update(dt){bin.x+=(bin.targetX-bin.w/2-bin.x)*Math.min(1,dt*11);bin.x=Math.max(0,Math.min(900-bin.w,bin.x));spawnClock+=dt;secondClock+=dt;if(spawnClock>=Math.max(.28,.72-(45-time)*.008)){spawnClock=0;spawn()}while(secondClock>=1){secondClock-=1;time--;updateHud();if(time<=0){end();return}}tapes=tapes.filter(t=>{t.y+=t.speed*dt;t.rotation+=t.spin*dt;if(hit(t,bin)){if(t.type==="cursed"){lives--;score=Math.max(0,score-25);beep(120,.1)}else{score+=t.type==="gold"?75:10;beep(t.type==="gold"?880:520)}updateHud();if(lives<=0)end();return false}return t.y<=590})}
  function drawTape(t){ctx.save();ctx.translate(t.x+t.w/2,t.y+t.h/2);ctx.rotate(t.rotation);ctx.translate(-t.w/2,-t.h/2);const colors=t.type==="cursed"?["#ff5c5c","#661313"]:t.type==="gold"?["#ffe66c","#9d6500"]:["#76d8ff","#144d67"],g=ctx.createLinearGradient(0,0,t.w,t.h);g.addColorStop(0,colors[0]);g.addColorStop(1,colors[1]);ctx.fillStyle=g;ctx.strokeStyle="rgba(255,255,255,.45)";ctx.lineWidth=2;rounded(0,0,t.w,t.h,7);ctx.fill();ctx.stroke();ctx.fillStyle="rgba(5,7,4,.72)";rounded(12,9,t.w-24,18,4);ctx.fill();ctx.restore()}
  function draw(){ctx.clearRect(0,0,900,560);ctx.fillStyle="#080d06";ctx.fillRect(0,0,900,560);ctx.strokeStyle="rgba(184,255,107,.07)";for(let x=0;x<900;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,560);ctx.stroke()}ctx.fillStyle="rgba(184,255,107,.55)";ctx.font="800 14px system-ui";ctx.fillText("DROP ZONE / EMPLOYEES ONLY",24,34);tapes.forEach(drawTape);ctx.fillStyle="#d7d8c8";ctx.strokeStyle="#5b6252";ctx.lineWidth=4;rounded(bin.x,bin.y,bin.w,bin.h,10);ctx.fill();ctx.stroke();ctx.fillStyle="#151913";ctx.fillRect(bin.x+14,bin.y+9,bin.w-28,14);ctx.fillStyle="#b8ff6b";ctx.textAlign="center";ctx.fillText("RETURN",bin.x+bin.w/2,bin.y+34);ctx.textAlign="left"}
  function loop(ts){if(!running)return;update(Math.min(.035,(ts-last)/1000||0));last=ts;draw();if(running)raf=requestAnimationFrame(loop)}
  function start(){if(raf)cancelAnimationFrame(raf);raf=0;reset();overlay.classList.add("hidden");overlay.setAttribute("aria-hidden","true");running=true;last=performance.now();raf=requestAnimationFrame(loop)}
  function end(){if(!running)return;running=false;if(raf)cancelAnimationFrame(raf);raf=0;if(score>best){best=score;try{localStorage.setItem(bestKey,String(best))}catch{}bestEl.textContent=best;title.textContent="New employee record."}else title.textContent=lives<=0?"The cursed tapes won.":"Shift complete.";copy.textContent=`You returned ${score} points worth of tapes. Management has converted this into zero dollars.`;startButton.textContent="Play again";overlay.classList.remove("hidden");overlay.removeAttribute("aria-hidden");beep(180,.2)}
  function move(x){const r=canvas.getBoundingClientRect();if(r.width)bin.targetX=(x-r.left)/r.width*900}
  stage.addEventListener("pointerdown",e=>{e.preventDefault();move(e.clientX);stage.setPointerCapture?.(e.pointerId)},{passive:false});stage.addEventListener("pointermove",e=>{if(e.buttons||e.pointerType==="touch"){e.preventDefault();move(e.clientX)}},{passive:false});addEventListener("keydown",e=>{if(e.key==="ArrowLeft"){e.preventDefault();bin.targetX-=85}if(e.key==="ArrowRight"){e.preventDefault();bin.targetX+=85}});
  startButton.addEventListener("click",start);muteButton?.addEventListener("click",()=>{sound=!sound;muteButton.textContent=`Sound: ${sound?"on":"off"}`;beep(660)});addEventListener("resize",resize);addEventListener("orientationchange",()=>setTimeout(resize,100));if("ResizeObserver" in window)new ResizeObserver(resize).observe(stage);resize();requestAnimationFrame(resize);
  window.__TAPE_PANIC_TEST__={start,end,getState:()=>({running,time,score,lives,raf,canvas:[canvas.width,canvas.height],binX:bin.x,targetX:bin.targetX}),move};
})();
